# Generated by Django 5.2.15 on 2026-06-04 06:33

import trading.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_tradingconfig_trading_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymarketcredentials',
            name='funder_address',
            field=models.CharField(blank=True, default='', help_text='Funder wallet address (0x…)', max_length=255),
        ),
        migrations.AlterField(
            model_name='polymarketcredentials',
            name='private_key',
            field=trading.encryption.EncryptedCharField(blank=True, default='', help_text='Polymarket EVM private key — stored encrypted'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='assets',
            field=models.CharField(default='BTC,ETH', help_text='Comma-separated list of assets to trade, e.g. BTC,ETH', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='deribit_neutral_high',
            field=models.FloatField(default=0.58, help_text='Upper bound of Deribit neutral band — skip entry if deribit_prob is below this (e.g. 0.58 means Deribit must be ≥58% for YES trade)'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='deribit_neutral_low',
            field=models.FloatField(default=0.42, help_text='Lower bound of Deribit neutral band — skip entry if deribit_prob is above this (e.g. 0.42 means Deribit must be ≤42% for NO trade)'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='positions_size_threshold',
            field=models.FloatField(default=0.01, help_text='Minimum position size to include in fetch (sizeThreshold)'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='redis_state_ttl_hours',
            field=models.FloatField(default=48.0, help_text='Hours before Redis trader-state keys expire (safety TTL)'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='today_lookahead_hours',
            field=models.FloatField(default=6.0, help_text="Hours added to now() when checking if a market resolves 'today'"),
        ),
    ]
